<?php

declare(strict_types=1);

namespace PMS\Schemas;

/**
 * Collection/table schemas and field definitions (MariaDB JSON document storage).
 * Used for validation and documentation.
 */
final class Collections
{
    public const USERS = 'users';
    public const STUDENTS = 'students';
    public const STAFF = 'staff';
    public const COMPANIES = 'companies';
    public const ALUMNI = 'alumni';
    public const DEPARTMENTS = 'departments';
    public const DRIVES = 'drives';
    public const APPLICATIONS = 'applications';
    public const JOBS = 'jobs';
    public const NOTIFICATIONS = 'notifications';
    public const REPORTS = 'reports';
    public const RULES = 'rules';
    public const BLACKLIST = 'blacklist';
    public const DRIVE_APPLICATION_EXCEPTIONS = 'drive_application_exceptions';
    public const RECOMMENDATIONS = 'recommendations';
    public const ALUMNI_REFERRALS = 'alumni_referrals';
    public const ALUMNI_JOB_POSTS = 'alumni_job_posts';
    public const INTERNAL_JOB_POSTS = 'internal_job_posts';
    public const INTERNAL_JOB_APPLICATIONS = 'internal_job_applications';
    public const CERTIFICATIONS = 'certifications';
    public const STUDENT_CERTIFICATIONS = 'student_certifications';
    public const STUDENT_DETAILS = 'student_details';
    public const STUDENT_PLACEMENTS = 'student_placements';
    public const PLACEMENT_OFFICERS = 'placement_officers';
    public const STUDENT_VOLUNTEERS = 'student_volunteers';
    public const RESUMES = 'resumes';
    public const RECRUITMENT_RESULTS = 'recruitment_results';
    public const SYSTEM_SETTINGS = 'system_settings';
    public const PUBLIC_PAGE_CONTENT = 'public_page_content';
    public const PLACEMENT_NEWS = 'placement_news';
    public const SUCCESS_STORIES = 'success_stories';
    public const POLICY_ACCEPTANCE_LOGS = 'policy_acceptance_logs';
    public const APTITUDE_TESTS = 'aptitude_tests';
    public const APTITUDE_ATTEMPTS = 'aptitude_attempts';
    public const APTITUDE_QUESTION_BANK = 'aptitude_question_bank';
    public const APTITUDE_JD_QUESTION_SETS = 'aptitude_jd_question_sets';
    public const SYLLABUS_QUESTION_BANK = 'syllabus_question_bank';
    public const SYLLABUS_MCQ_TESTS = 'syllabus_mcq_tests';
    public const SYLLABUS_AUTONOMOUS_MCQ_ATTEMPTS = 'syllabus_autonomous_mcq_attempts';
    public const STUDENT_AI_PRACTICE_SESSIONS = 'student_ai_practice_sessions';
    public const CODING_TESTS = 'coding_tests';
    public const CODING_ATTEMPTS = 'coding_attempts';
    public const CODING_PROBLEM_BANK = 'coding_problem_bank';
    public const CODING_PRACTICE_SUBMISSIONS = 'coding_practice_submissions';
    public const CODING_COMPANY_PROBLEM_SETS = 'coding_company_problem_sets';
    public const TUTORIAL_CATEGORIES = 'tutorial_categories';
    public const TUTORIALS = 'tutorials';
    public const TUTORIAL_MODULES = 'tutorial_modules';
    public const TUTORIAL_EXERCISES = 'tutorial_exercises';
    public const TUTORIAL_TEST_CASES = 'tutorial_test_cases';
    public const STUDENT_TUTORIAL_PROGRESS = 'student_tutorial_progress';
    public const STUDENT_TUTORIAL_MODULE_PROGRESS = 'student_tutorial_module_progress';
    public const STUDENT_EXERCISE_ATTEMPTS = 'student_exercise_attempts';
    public const TUTORIAL_MODULE_ASSESSMENTS = 'tutorial_module_assessments';
    public const TUTORIAL_MODULE_QUESTIONS = 'tutorial_module_questions';
    public const TUTORIAL_MODULE_ASSESSMENT_ATTEMPTS = 'tutorial_module_assessment_attempts';
    public const TUTORIAL_MODULE_ASSESSMENT_ANSWERS = 'tutorial_module_assessment_answers';
    public const TUTORIAL_MODULE_ACTIVITIES = 'tutorial_module_activities';
    public const TUTORIAL_MODULE_ACTIVITY_SUBMISSIONS = 'tutorial_module_activity_submissions';
    public const TUTORIAL_MODULE_ACTIVITY_REVIEWS = 'tutorial_module_activity_reviews';
    public const TUTORIAL_LESSON_QUESTIONS = 'tutorial_lesson_questions';
    public const TUTORIAL_LESSON_QUESTION_ATTEMPTS = 'tutorial_lesson_question_attempts';
    public const RESUME_CAREER_OBJECTIVES = 'resume_career_objectives';
    public const RESUME_SKILLS = 'resume_skills';
    public const RESUME_PROJECTS = 'resume_projects';
    public const RESUME_EXPERIENCE = 'resume_experience';
    public const RESUME_CERTIFICATIONS = 'resume_certifications';
    public const RESUME_ACTIVITIES = 'resume_activities';
    public const RESUME_CONTACT_LINKS = 'resume_contact_links';

    /** Valid user roles */
    public const ROLES = [
        'admin',
        'student',
        'staff',
        'company',
        'alumni',
        'placement_officer',
    ];

    public const USER_STATUS = ['active', 'blocked', 'pending'];

    public const APPLICATION_STATUS = [
        'applied',
        'resume_pending',
        'resume_verified',
        'officer_approved',
        'company_review',
        'shortlisted',
        'selected',
        'rejected',
        'withdrawn',
    ];

    public const DRIVE_TYPES = ['exclusive', 'pooled', 'direct'];

    public const COMPANY_TIERS = ['Tier 1', 'Tier 2', 'Tier 3'];

    public const COMPANY_CATEGORIES = [
        'Software',
        'Mechanical',
        'Chemical',
        'Food',
        'Production',
    ];

    /**
     * Default document shapes for each collection.
     *
     * @return array<string, array<string, mixed>>
     */
    public static function schemas(): array
    {
        return [
            self::USERS => [
                '_id'       => 'ObjectId',
                'name'      => 'string',
                'email'     => 'string',
                'password'  => 'string (bcrypt hash)',
                'role'      => 'string (enum)',
                'status'    => 'string (active|blocked|pending)',
                'approved'  => 'bool',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::STUDENTS => [
                '_id'            => 'ObjectId',
                'userId'         => 'ObjectId',
                'registerNumber' => 'string',
                'departmentId'   => 'ObjectId',
                'personal'       => [
                    'phone'          => 'string',
                    'personalEmail'  => 'string',
                    'address'        => 'string',
                    'dob'            => 'string',
                    'gender'         => 'string',
                    'maritalStatus'  => 'string (Single|Married|Other)',
                ],
                'academic' => [
                    'ugMarks'    => 'float',
                    'mcaMarks'   => 'float',
                    'marks10th'  => 'float',
                    'marks12th'  => 'float',
                    'cgpa'       => 'float',
                    'backlogs'   => 'int',
                    'semesters'  => 'array',
                ],
                'certifications' => 'array[{name, issuer, year}]',
                'resume'         => [
                    'filename'   => 'string',
                    'path'       => 'string',
                    'verified'   => 'bool',
                    'uploadedAt' => 'UTCDateTime',
                ],
                'policyAccepted' => 'bool',
                'policyAcceptedAt' => 'string',
                'policyVersion' => 'string',
                'placementPolicyAccepted' => 'bool',
                'placementPolicyAcceptedAt' => 'string',
                'placementPolicyVersion' => 'string',
                'internshipPolicyAccepted' => 'bool',
                'internshipPolicyAcceptedAt' => 'string',
                'internshipPolicyVersion' => 'string',
                'placementRegistration' => 'array|null',
                'signedReport'   => 'string|null',
                'selfPlacement'  => 'array|null',
                'placementChances' => [
                    'used'      => 'int',
                    'remaining' => 'int',
                ],
                'placed'         => 'bool',
                'placement'      => 'array|null',
                'placementHistory'=> 'array',
                'createdAt'      => 'UTCDateTime',
                'updatedAt'      => 'UTCDateTime',
            ],
            self::RESUMES => [
                '_id'        => 'ObjectId',
                'userId'     => 'ObjectId (student user)',
                'studentId'  => 'ObjectId',
                'label'      => 'string',
                'profileType'=> 'string',
                'fileName'   => 'string',
                'fileSize'   => 'int',
                'mime'       => 'string',
                'storedName' => 'string (server filename)',
                'verified'   => 'bool',
                'isDefault'  => 'bool',
                'uploadedAt' => 'UTCDateTime',
                'createdAt'  => 'UTCDateTime',
                'updatedAt'  => 'UTCDateTime',
            ],
            self::STAFF => [
                '_id'       => 'ObjectId',
                'userId'    => 'ObjectId',
                'departmentId' => 'ObjectId|null',
                'designation' => 'string',
                'staffRank' => 'int|null',
                'isHod'     => 'bool',
                'createdAt' => 'UTCDateTime',
            ],
            self::PLACEMENT_OFFICERS => [
                '_id'          => 'ObjectId',
                'userId'       => 'ObjectId',
                'departmentId' => 'ObjectId (unique — one placement officer per department)',
                'designation'  => 'string',
                'createdAt'    => 'UTCDateTime',
                'updatedAt'    => 'UTCDateTime',
            ],
            self::STUDENT_VOLUNTEERS => [
                '_id'          => 'ObjectId',
                'studentId'    => 'ObjectId',
                'userId'       => 'ObjectId|null',
                'departmentId' => 'ObjectId',
                'assignedBy'   => 'ObjectId',
                'assignedAt'   => 'UTCDateTime',
                'academicYear' => 'string (e.g. 2026–2027, July–June)',
                'offerLetter'  => 'object|null (draft/published PCA letter fields)',
                'status'       => 'string (active|removed)',
                'notes'        => 'string|null',
                'removeReason' => 'string|null',
                'removedAt'    => 'UTCDateTime|null',
                'removedBy'    => 'ObjectId|null',
                'createdAt'    => 'UTCDateTime',
                'updatedAt'    => 'UTCDateTime',
            ],
            self::COMPANIES => [
                '_id'           => 'ObjectId',
                'userId'        => 'ObjectId|null',
                'companyName'   => 'string',
                'nameNormalized' => 'string|null (dedupe key)',
                'category'      => 'string (enum)',
                'tier'          => 'string (enum)',
                'contacts'      => 'array[{name, email, phone, designation}]',
                'recruitmentHistory' => 'array',
                'associationStatus'  => 'string (active|inactive|pending)',
                'comments'           => 'string',
                'website'       => 'string',
                'description'   => 'string',
                'location'      => 'string',
                'recruiterPhoto' => 'object|null',
                'logo'           => 'object|null (company logo upload)',
                'createdAt'     => 'UTCDateTime',
                'updatedAt'     => 'UTCDateTime',
            ],
            self::ALUMNI => [
                '_id'        => 'ObjectId',
                'userId'     => 'ObjectId',
                'company'    => 'string',
                'role'       => 'string (job title)',
                'package'    => 'string',
                'experience' => 'int (years)',
                'skills'     => 'array',
                'isWorking'  => 'bool',
                'employmentDocs' => 'array|null',
                'createdAt'  => 'UTCDateTime',
                'updatedAt'  => 'UTCDateTime',
            ],
            self::ALUMNI_REFERRALS => [
                '_id'            => 'ObjectId',
                'alumniUserId'   => 'ObjectId',
                'jobTitle'       => 'string',
                'companyName'    => 'string',
                'description'    => 'string',
                'link'           => 'string (company website)',
                'package'        => 'string',
                'referralType'   => 'string (Student|Alumni|Either)',
                'status'         => 'string (submitted|in_review|accepted)',
                'createdAt'      => 'UTCDateTime',
                'updatedAt'      => 'UTCDateTime',
            ],
            self::ALUMNI_JOB_POSTS => [
                '_id'          => 'ObjectId',
                'alumniUserId' => 'ObjectId|null',
                'staffUserId'  => 'ObjectId|null',
                'ownerUserId'  => 'ObjectId',
                'sourceType'   => 'string (alumni|staff)',
                'title'        => 'string',
                'company'      => 'string',
                'jobType'      => 'string',
                'package'      => 'string',
                'location'     => 'string',
                'description'  => 'string',
                'imageUrl'     => 'string',
                'posterUrl'    => 'string',
                'posterType'   => 'string (image|pdf)',
                'status'       => 'string (pending|open|reviewing|closed|rejected)',
                'audience'     => 'string (student|alumni|both)',
                'eligibility'  => 'object{branches:array,departments:array}',
                'departmentId' => 'ObjectId',
                'driveId'      => 'ObjectId|null',
                'approvedBy'   => 'ObjectId|null',
                'approvedAt'   => 'UTCDateTime|null',
                'rejectedReason' => 'string',
                'views'        => 'int',
                'createdAt'    => 'UTCDateTime',
                'updatedAt'    => 'UTCDateTime',
            ],
            self::INTERNAL_JOB_POSTS => [
                '_id' => 'ObjectId',
                'jobType' => 'string (part_time|internship)',
                'title' => 'string',
                'company' => 'string',
                'departmentId' => 'string (first selected department)',
                'departmentIds' => 'string[]',
                'departments' => 'array<{id,code,name}>',
                'departmentCode' => 'string',
                'departmentName' => 'string',
                'description' => 'string',
                'requiredSkills' => 'string',
                'eligibilityCriteria' => 'string',
                'minCgpa' => 'float|null',
                'vacancies' => 'int',
                'workLocation' => 'string',
                'workMode' => 'string (online|offline)',
                'startDate' => 'string',
                'endDate' => 'string',
                'duration' => 'string',
                'workingHours' => 'string',
                'stipend' => 'string (part-time, required to publish)',
                'compensationType' => 'string (unpaid|fee|stipend)',
                'compensationAmount' => 'string',
                'paymentFrequency' => 'string (monthly|weekly|one_time)',
                'applicationDeadline' => 'string',
                'contactInformation' => 'string',
                'additionalRequirements' => 'string',
                'attachment' => 'object|null',
                'status' => 'string (draft|published|closed)',
                'createdBy' => 'string',
                'createdByRole' => 'string (admin|placement_officer)',
                'publishedAt' => 'UTCDateTime|null',
                'closedAt' => 'UTCDateTime|null',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::INTERNAL_JOB_APPLICATIONS => [
                '_id' => 'ObjectId',
                'postId' => 'string',
                'studentUserId' => 'string',
                'studentName' => 'string',
                'registerNumber' => 'string',
                'departmentId' => 'string',
                'departmentCode' => 'string',
                'classBatch' => 'string',
                'status' => 'string (applied)',
                'appliedAt' => 'UTCDateTime',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::CERTIFICATIONS => [
                '_id' => 'ObjectId',
                'name' => 'string',
                'url' => 'string',
                'dueDate' => 'string (YYYY-MM-DD, Asia/Kolkata calendar date)',
                'description' => 'string',
                'visibility' => 'string (all|departments)',
                'departmentIds' => 'array of department ids',
                'createdBy' => 'ObjectId',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::STUDENT_CERTIFICATIONS => [
                '_id' => 'ObjectId',
                'studentId' => 'ObjectId',
                'certificationId' => 'ObjectId',
                'pairKey' => 'string (studentId:certificationId, unique)',
                'status' => 'string (pending|completed)',
                'proofPath' => 'string',
                'proofFileName' => 'string',
                'completedAt' => 'UTCDateTime|null',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::STUDENT_DETAILS => [
                '_id' => 'ObjectId',
                'aesAdmno' => 'string (unique AES admission number)',
                'registerNumber' => 'string',
                'studentName' => 'string',
                'displayName' => 'string',
                'classBatch' => 'string',
                'programme' => 'string',
                'branch' => 'string',
                'year' => 'string',
                'semester' => 'string',
                'courseId' => 'string',
                'branchId' => 'string',
                'deptAesId' => 'string',
                'email' => 'string',
                'phone' => 'string',
                'photoUrl' => 'string',
                'studRole' => 'string (student|alumni)',
                'registrationStatus' => 'string|null (registered|non_registered; null for alumni)',
                'syncSource' => 'string',
                'syncedAt' => 'string',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::STUDENT_PLACEMENTS => [
                '_id' => 'ObjectId',
                'pairKey' => 'string (studentId, unique)',
                'studentId' => 'ObjectId',
                'registerNumber' => 'string',
                'departmentId' => 'ObjectId|null',
                'classBatch' => 'string (stud_class at save — passed-out cohorts)',
                'programme' => 'string',
                'branch' => 'string',
                'studentName' => 'string',
                'courseId' => 'string',
                'branchId' => 'string',
                'phone' => 'string',
                'email' => 'string',
                'admissionNo' => 'string',
                'company' => 'string',
                'role' => 'string',
                'package' => 'string',
                'address' => 'string',
                'employerContact' => 'string',
                'joinDate' => 'string',
                'endDate' => 'string',
                'academicDuration' => 'string',
                'internshipDetails' => 'string',
                'natureOfJob' => 'string',
                'monthlySalary' => 'string',
                'placementStatus' => 'string',
                'offerLetterVerified' => 'bool',
                'verificationDate' => 'string',
                'fordvv' => 'string',
                'includedvv' => 'string',
                'recordType' => 'string (Placement|Higher Education|Research)',
                'offerLetter' => 'string|null',
                'joiningLetter' => 'string|null',
                'companyIdDoc' => 'string|null',
                'updatedAt' => 'UTCDateTime',
                'createdAt' => 'UTCDateTime',
            ],
            self::TUTORIAL_CATEGORIES => [
                '_id' => 'ObjectId',
                'name' => 'string',
                'slug' => 'string (unique)',
                'description' => 'string',
                'status' => 'string (active|inactive)',
                'createdBy' => 'ObjectId|empty',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::TUTORIALS => [
                '_id' => 'ObjectId',
                'title' => 'string',
                'categoryId' => 'ObjectId',
                'topic' => 'string (free text, not a language enum)',
                'description' => 'string',
                'thumbnail' => 'string',
                'status' => 'string (draft|published|unpublished)',
                'visibility' => 'string (all|scoped)',
                'departmentIds' => 'array of existing department ids',
                'passingYears' => 'array of four-digit passout years',
                'createdBy' => 'ObjectId|empty',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::TUTORIAL_MODULES => [
                '_id' => 'ObjectId',
                'tutorialId' => 'ObjectId',
                'title' => 'string',
                'sortOrder' => 'int',
                'content' => 'string (HTML stored for a later editor)',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::TUTORIAL_EXERCISES => [
                '_id' => 'ObjectId',
                'moduleId' => 'ObjectId',
                'title' => 'string',
                'instructions' => 'string',
                'language' => 'string (normalized label, not a compiler id)',
                'boilerplate' => 'string',
                'timeLimitMs' => 'int',
                'memoryLimitKb' => 'int',
                'sortOrder' => 'int',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::TUTORIAL_TEST_CASES => [
                '_id' => 'ObjectId',
                'exerciseId' => 'ObjectId',
                'stdin' => 'string',
                'expectedOutput' => 'string (may be empty)',
                'sample' => 'bool (true = public sample, false = hidden)',
                'sortOrder' => 'int',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::STUDENT_TUTORIAL_PROGRESS => [
                '_id' => 'ObjectId',
                'studentId' => 'ObjectId (student profile, one row per tutorial)',
                'tutorialId' => 'ObjectId',
                'pairKey' => 'string (studentId:tutorialId, unique)',
                'startedAt' => 'UTCDateTime|null',
                'completedAt' => 'UTCDateTime|null',
                'lastVisitedModuleId' => 'ObjectId|null',
                'progressPercent' => 'int (server calculated)',
                'status' => 'string (NOT_STARTED|IN_PROGRESS|COMPLETED)',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::STUDENT_TUTORIAL_MODULE_PROGRESS => [
                '_id' => 'ObjectId',
                'studentId' => 'ObjectId',
                'tutorialId' => 'ObjectId',
                'moduleId' => 'ObjectId',
                'pairKey' => 'string (studentId:moduleId, unique)',
                'completedAt' => 'UTCDateTime',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::STUDENT_EXERCISE_ATTEMPTS => [
                '_id' => 'ObjectId',
                'studentId' => 'ObjectId',
                'tutorialId' => 'ObjectId',
                'moduleId' => 'ObjectId',
                'exerciseId' => 'ObjectId',
                'language' => 'string',
                'sourceCode' => 'string',
                'status' => 'string (ATTEMPTED)',
                'testsPassed' => 'null until an execution engine exists',
                'testsTotal' => 'null until an execution engine exists',
                'submittedAt' => 'UTCDateTime',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::TUTORIAL_MODULE_ASSESSMENTS => [
                '_id' => 'ObjectId',
                'tutorialId' => 'ObjectId',
                'moduleId' => 'ObjectId (unique active assessment per module)',
                'title' => 'string',
                'status' => 'string (draft|published)',
                'passPercent' => 'int',
                'maxAttempts' => 'int',
                'showExplanations' => 'bool',
                'allowReview' => 'bool',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::TUTORIAL_MODULE_QUESTIONS => [
                '_id' => 'ObjectId',
                'assessmentId' => 'ObjectId',
                'question' => 'string',
                'options' => 'array[4] of string',
                'correctIndex' => 'int 0-3 (staff only)',
                'explanation' => 'string',
                'difficulty' => 'string (beginner|intermediate|advanced)',
                'marks' => 'int',
                'sortOrder' => 'int',
                'archived' => 'bool (soft-retired on assessment edit; kept for historical attempts)',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::TUTORIAL_MODULE_ASSESSMENT_ATTEMPTS => [
                '_id' => 'ObjectId',
                'studentId' => 'ObjectId',
                'assessmentId' => 'ObjectId',
                'tutorialId' => 'ObjectId',
                'moduleId' => 'ObjectId',
                'attemptNumber' => 'int',
                'pairKey' => 'string (studentId:assessmentId:attemptNumber unique)',
                'score' => 'int',
                'totalMarks' => 'int',
                'percent' => 'int',
                'passed' => 'bool',
                'status' => 'string (IN_PROGRESS|SUBMITTED)',
                'questionSnapshot' => 'array of immutable question copies used for scoring/review (server-only)',
                'startedAt' => 'UTCDateTime',
                'submittedAt' => 'UTCDateTime|null',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::TUTORIAL_MODULE_ASSESSMENT_ANSWERS => [
                '_id' => 'ObjectId',
                'attemptId' => 'ObjectId',
                'questionId' => 'ObjectId',
                'pairKey' => 'string (attemptId:questionId unique)',
                'selectedIndex' => 'int 0-3',
                'isCorrect' => 'bool',
                'marksAwarded' => 'int',
                'questionSnapshot' => 'object|null (immutable question copy at submit)',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::TUTORIAL_MODULE_ACTIVITIES => [
                '_id' => 'ObjectId',
                'tutorialId' => 'ObjectId',
                'moduleId' => 'ObjectId',
                'title' => 'string',
                'instructions' => 'string (sanitized)',
                'activityType' => 'string (programming_task|sql_query|numerical|short_answer|case_study|analytical_design)',
                'academicField' => 'string (engineering|computer_applications|business_administration|other)',
                'difficulty' => 'string (beginner|intermediate|advanced)',
                'sortOrder' => 'int',
                'status' => 'string (draft|published)',
                'evaluationMode' => 'string (none|self_check|tutor_review|auto_compare)',
                'config' => 'object (type-specific)',
                'answerKey' => 'object (staff-only; never student-facing)',
                'archived' => 'bool',
                'createdBy' => 'ObjectId',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::TUTORIAL_MODULE_ACTIVITY_SUBMISSIONS => [
                '_id' => 'ObjectId',
                'activityId' => 'ObjectId',
                'tutorialId' => 'ObjectId',
                'moduleId' => 'ObjectId',
                'studentId' => 'ObjectId (student profile id from session)',
                'attemptNumber' => 'int (server assigned)',
                'pairKey' => 'string (studentId:activityId:attemptNumber unique)',
                'status' => 'string (IN_PROGRESS|SUBMITTED|RETURNED)',
                'payload' => 'object (type-specific student response; never includes scores)',
                'autoResult' => 'object|null (server evaluation only; never client-supplied)',
                'activitySnapshot' => 'object (immutable activity definition + server-only answerKey)',
                'startedAt' => 'UTCDateTime',
                'submittedAt' => 'UTCDateTime|null',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::TUTORIAL_MODULE_ACTIVITY_REVIEWS => [
                '_id' => 'ObjectId',
                'submissionId' => 'ObjectId (unique current review)',
                'activityId' => 'ObjectId',
                'reviewerUserId' => 'ObjectId',
                'score' => 'float|null',
                'maxScore' => 'float|null',
                'passed' => 'bool|null',
                'feedback' => 'string (student-visible)',
                'privateNotes' => 'string (staff-only)',
                'status' => 'string (pending|reviewed)',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::DEPARTMENTS => [
                '_id'       => 'ObjectId',
                'name'      => 'string',
                'code'      => 'string',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::DRIVES => [
                '_id'         => 'ObjectId',
                'title'       => 'string',
                'companyId'   => 'ObjectId',
                'type'        => 'string (exclusive|pooled|direct)',
                'date'        => 'string',
                'time'        => 'string',
                'branches'    => 'array (department codes)',
                'eligibility' => [
                    'minCgpa'      => 'float',
                    'maxBacklogs'  => 'int',
                    'minPercentAllClasses' => 'float',
                    'min10th'      => 'float',
                    'min12th'      => 'float',
                    'minUg'        => 'float',
                    'minPg'        => 'float',
                    'gender'       => 'string (any|male|female)',
                    'skills'       => 'array',
                ],
                'selectionRounds' => 'array[{order:int,type:string,label:string}]',
                'roundProgression' => 'string (sequential|parallel)',
                'applicationFields' => 'array[{id:string,title:string,required:bool}]',
                'tier'        => 'string',
                'jdFile'      => 'string|null',
                'shortlistDocument' => 'string|null (server path; stripped from API)',
                'shortlistDocumentName' => 'string|null',
                'shortlistUploadedAt' => 'string|null (ISO)',
                'shortlistUploadedBy' => 'ObjectId|null',
                'attendance'  => 'array[{studentId, present}]',
                'results'     => 'array',
                'status'      => 'string (scheduled|ongoing|completed)',
                'createdBy'   => 'ObjectId',
                'departmentId'=> 'ObjectId|null (officer department for dept-wise drives)',
                'createdAt'   => 'UTCDateTime',
                'updatedAt'   => 'UTCDateTime',
            ],
            self::APPLICATIONS => [
                '_id'       => 'ObjectId',
                'studentId' => 'ObjectId',
                'driveId'   => 'ObjectId',
                'companyId' => 'ObjectId',
                'jobId'     => 'ObjectId|null',
                'status'    => 'string (workflow enum)',
                'remarks'   => 'string',
                'timeline'  => 'array[{status, at, by}]',
                'roundOutcomes' => 'array[{order:int,type:string,status:string,updatedAt,updatedBy}]',
                'customAnswers' => 'array[{fieldId,title,value}]',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::JOBS => [
                '_id'         => 'ObjectId',
                'companyId'   => 'ObjectId',
                'ownerUserId' => 'ObjectId|null',
                'sourceType'  => 'string (company)',
                'companyName' => 'string',
                'driveId'     => 'ObjectId|null',
                'title'       => 'string',
                'description' => 'string',
                'jdFile'      => 'string|null',
                'imageUrl'    => 'string',
                'posterUrl'   => 'string',
                'posterType'  => 'string (image|pdf)',
                'eligibility' => [
                    'minCgpa'     => 'float',
                    'departments' => 'array',
                    'skills'      => 'array',
                    'maxBacklogs' => 'int',
                    'branches'    => 'array',
                    'min10th'     => 'float',
                    'min12th'     => 'float',
                    'notes'       => 'string',
                ],
                'package'     => 'string',
                'location'    => 'string',
                'jobType'     => 'string',
                'status'      => 'string (open|reviewing|closed)',
                'audience'    => 'string (student|alumni|both)',
                'openings'    => 'int',
                'createdAt'   => 'UTCDateTime',
                'updatedAt'   => 'UTCDateTime',
            ],
            self::NOTIFICATIONS => [
                '_id'       => 'ObjectId',
                'userId'    => 'ObjectId',
                'type'      => 'string',
                'title'     => 'string',
                'message'   => 'string',
                'read'      => 'bool',
                'metadata'  => 'object',
                'createdAt' => 'UTCDateTime',
            ],
            self::REPORTS => [
                '_id'       => 'ObjectId',
                'type'      => 'string (company|student|monthly)',
                'filename'  => 'string',
                'path'      => 'string',
                'generatedBy' => 'ObjectId',
                'filters'   => 'object',
                'createdAt' => 'UTCDateTime',
            ],
            self::RULES => [
                '_id'               => 'ObjectId',
                'name'              => 'string',
                'minCgpa'           => 'float',
                'maxBacklogs'       => 'int',
                'placementChances'  => 'int',
                'eligibilityCriteria' => 'string',
                'tierRules'         => 'object',
                'active'            => 'bool',
                'createdAt'         => 'UTCDateTime',
                'updatedAt'         => 'UTCDateTime',
            ],
            self::BLACKLIST => [
                '_id'       => 'ObjectId',
                'studentId' => 'ObjectId',
                'reason'    => 'string',
                'blacklistedBy' => 'ObjectId',
                'createdAt' => 'UTCDateTime',
                'removedAt' => 'UTCDateTime|null',
            ],
            self::RECOMMENDATIONS => [
                '_id'            => 'ObjectId',
                'staffId'        => 'ObjectId',
                'companyName'    => 'string',
                'companyWebsite' => 'string',
                'category'       => 'string',
                'reason'         => 'string',
                'contact'        => ['name' => 'string', 'email' => 'string', 'phone' => 'string'],
                'status'         => 'string',
                'createdAt'      => 'UTCDateTime',
                'updatedAt'      => 'UTCDateTime',
            ],
            self::RECRUITMENT_RESULTS => [
                '_id'           => 'ObjectId',
                'studentName'   => 'string',
                'registerNumber'=> 'string',
                'departmentId'  => 'ObjectId|null',
                'classBatch'    => 'string',
                'company'       => 'string',
                'role'          => 'string',
                'package'       => 'string',
                'status'        => 'string (selected|rejected)',
                'joiningDate'   => 'string (YYYY-MM-DD)',
                'createdAt'     => 'UTCDateTime',
                'updatedAt'     => 'UTCDateTime',
            ],
            self::SYSTEM_SETTINGS => [
                '_id'              => 'ObjectId',
                'key'              => 'string (default)',
                'placementYear'    => 'string',
                'emailFrom'        => 'string',
                'maxUploadMb'      => 'int',
                'smtpEnabled'      => 'bool',
                'notifyOnApproval' => 'bool',
                'createdAt'        => 'UTCDateTime',
                'updatedAt'        => 'UTCDateTime',
            ],
            self::PUBLIC_PAGE_CONTENT => [
                '_id'          => 'ObjectId',
                'key'          => 'string (default)',
                'season'       => 'string',
                'placed'       => 'int',
                'companies'    => 'int',
                'highestPkg'   => 'float',
                'avgPkg'       => 'float',
                'medianPkg'    => 'float',
                'lowestPkg'    => 'float',
                'headline'     => 'string',
                'achievements' => 'string',
                'createdAt'    => 'UTCDateTime',
                'updatedAt'    => 'UTCDateTime',
            ],
            self::PLACEMENT_NEWS => [
                '_id'       => 'ObjectId',
                'title'     => 'string',
                'summary'   => 'string',
                'date'      => 'string (YYYY-MM-DD)',
                'link'      => 'string',
                'createdAt' => 'UTCDateTime',
                'updatedAt' => 'UTCDateTime',
            ],
            self::SUCCESS_STORIES => [
                '_id'          => 'ObjectId',
                'alumniUserId' => 'ObjectId',
                'alumniName'   => 'string',
                'name'         => 'string',
                'company'      => 'string',
                'role'         => 'string',
                'package'      => 'string',
                'quote'        => 'string',
                'status'       => 'string (published)',
                'createdAt'    => 'UTCDateTime',
                'updatedAt'    => 'UTCDateTime',
            ],
            self::APTITUDE_TESTS => [
                '_id'             => 'ObjectId',
                'title'           => 'string',
                'description'     => 'string',
                'category'        => 'string (Quantitative Aptitude|Logical Reasoning|Verbal Ability|Data Interpretation|Numerical Ability|General Aptitude)',
                'difficulty'      => 'string (Easy|Medium|Hard)',
                'questionCount'   => 'int',
                'durationMinutes' => 'int (duration)',
                'totalMarks'      => 'float (total_marks)',
                'negativeMarking' => 'bool',
                'negativeMarks'   => 'float (negative_mark)',
                'instructions'    => 'string',
                'status'          => 'string (published|unpublished)',
                'questionType'    => 'string (mcq)',
                'questions'       => 'array AptitudeQuestion/TestQuestion[{id,question_order via index,prompt|question_text,options,correctIndex|correct_answer,explanation,marks,negative_marks,category,difficulty}]',
                'departmentId'    => 'ObjectId|null (optional — unset = institution-wide; PO tests scoped to department)',
                'createdBy'       => 'ObjectId|null (created_by)',
                'createdAt'       => 'UTCDateTime',
                'updatedAt'       => 'UTCDateTime',
            ],
            self::APTITUDE_ATTEMPTS => [
                '_id'             => 'ObjectId',
                'testId'          => 'ObjectId (test_id)',
                'userId'          => 'ObjectId (user_id — subject; never trust client for ownership)',
                'studentId'       => 'ObjectId|null',
                'alumniId'        => 'ObjectId|null',
                'departmentId'    => 'ObjectId|null',
                'classBatch'      => 'string',
                'subjectType'     => 'string (student|alumni|staff)',
                'status'          => 'string (in_progress|completed)',
                'answers'         => 'object AttemptAnswer map questionId=>selectedIndex',
                'questionAnalysis'=> 'array AttemptAnswer[{questionId,selectedIndex|selected_answer,isCorrect,marksObtained}]',
                'score'           => 'float',
                'marksObtained'   => 'float',
                'totalMarks'      => 'float',
                'percentage'      => 'float',
                'accuracy'        => 'float',
                'correctCount'    => 'int',
                'wrongCount'      => 'int (incorrect_count)',
                'unansweredCount' => 'int',
                'timeTakenSeconds'=> 'int (time_taken)',
                'categoryScores'  => 'object',
                'startedAt'       => 'UTCDateTime',
                'completedAt'     => 'UTCDateTime|null (submitted_at)',
                'submittedAt'     => 'UTCDateTime|null',
            ],
            self::APTITUDE_QUESTION_BANK => [
                '_id'          => 'ObjectId',
                'prompt'       => 'string (question_text)',
                'options'      => 'array',
                'correctIndex' => 'int (correct_answer)',
                'explanation'  => 'string',
                'marks'        => 'float',
                'category'     => 'string',
                'difficulty'   => 'string',
                'createdBy'    => 'ObjectId|null',
            ],
            self::SYLLABUS_QUESTION_BANK => [
                '_id'          => 'ObjectId',
                'courseCode'   => 'string',
                'courseTitle'  => 'string',
                'semsubId'     => 'string',
                'department'   => 'string',
                'module'       => 'string',
                'question'     => 'string',
                'options'      => 'array',
                'correctIndex' => 'int',
                'explanation'  => 'string',
                'difficulty'   => 'string',
                'createdBy'    => 'ObjectId|null',
            ],
        ];
    }
}
